# Variant zoo — the search space, as data.
# kind: "env"  -> run the base binary with env vars (7 s/variant)
#       "patch"-> generate zoo/build/mein_<name>.cpp via exact-string substitutions (must each hit
#                 EXACTLY once or the variant is skipped with an error), build, run. (~30 s build)
# expect: judge-known or theory sign used for the CONTROLS acceptance test: "+" better, "-" worse,
#         "0" no change, "?" unknown (the actual screen).
# Every substitution anchor was grep-verified against solver/mein.cpp on 2026-07-14.

BASE_RUNG = 6610

VARIANTS = [
    # ---------- CONTROLS (instrument acceptance: known signs must reproduce) ----------
    dict(name="base_a",     family="control", kind="env", env={}, expect="0",
         note="reference run 1 (determinism check vs base_b/base_c)"),
    dict(name="base_b",     family="control", kind="env", env={}, expect="0", note="reference run 2"),
    dict(name="base_c",     family="control", kind="env", env={}, expect="0", note="reference run 3"),
    dict(name="traj_a",     family="control", kind="env", env={"G_CTB": "6.45"}, expect="0",
         note="tail box -0.05s: pure trajectory re-roll -> measures the local draw sigma (noise floor)"),
    dict(name="traj_b",     family="control", kind="env", env={"G_CTB": "6.55"}, expect="0",
         note="tail box +0.05s: second trajectory re-roll"),
    dict(name="rim_off",    family="control", kind="env", env={"G_RIMK": "0"}, expect="-",
         note="RIM-BUDGET off. Judge-VALIDATED positive (c3 wall 6700->6610) => faithful ruler must read NEGATIVE"),
    dict(name="rim_035",    family="control", kind="env", env={"G_RIMK": "0.35"}, expect="-",
         note="half rim strength: must sit between rim_off and base (monotonicity anchor)"),
    dict(name="tail_off",   family="control", kind="env", env={"G_LAZY": "0", "G_CTK": "0"}, expect="0",
         note="MEASURED DUPE(base) on this fork: Decimate already reaches c3t so the tail loop is a "
              "no-op at 6610 here (90.51-era flow). Tail-family variants (pool/ctb/rb/mpc/traj) are "
              "therefore UNINFORMATIVE on this branch - port the zoo to the team HEAD to screen them."),
    dict(name="qw_005",     family="control", kind="patch", expect="-",
         subs=[("static double qweight_for(int) { return 0.0; }",
                "static double qweight_for(int) { return 0.05; }")],
         note="qweight 0.05: judge-WA'd #19885312 => must read NEGATIVE"),
    dict(name="areaq",      family="control", kind="patch", expect="-",
         subs=[("const Quadric Kf = p * p.transpose();",
                "const Quadric Kf = (0.5 * len) * (p * p.transpose());")],
         note="area-weighted quadrics: HURT c4/c6 on the judge => expect <=0 here"),
    dict(name="nplace_off", family="control", kind="patch", expect="-",
         subs=[("g_nplace = g_ndecim;", "g_nplace = 0;")],
         note="normal-optimal placement off (+0.0006 c3 when shipped) => must read NEGATIVE"),

    # ---------- A. ORDERING (edge-priority: which collapse goes first) ----------
    dict(name="rim_100",    family="ordering", kind="env", env={"G_RIMK": "1.0"}, expect="?",
         note="rim-budget stronger than banked 0.7 (allocation-strength curve, judge-positive class)"),
    dict(name="rim_140",    family="ordering", kind="env", env={"G_RIMK": "1.4"}, expect="?",
         note="rim-budget 2x banked"),
    dict(name="rim_200",    family="ordering", kind="env", env={"G_RIMK": "2.0"}, expect="?",
         note="rim-budget ~3x: where does over-allocation start hurting?"),
    dict(name="lam_8",      family="ordering", kind="patch", expect="?",
         subs=[("if (V > 7000   && V <= 30000)  return 16.0;",
                "if (V > 7000   && V <= 30000)  return 8.0;")],
         note="Pivot-A lambda 16->8 (deficit-steering strength down)"),
    dict(name="lam_24",     family="ordering", kind="patch", expect="?",
         subs=[("if (V > 7000   && V <= 30000)  return 16.0;",
                "if (V > 7000   && V <= 30000)  return 24.0;")],
         note="Pivot-A lambda 16->24 (steering up; 24 WA'd once at an old rung - re-screen on faithful ruler)"),
    dict(name="alloc_05",   family="ordering", kind="env", env={"G_ALLOC_WEIGHT": "0.5"}, expect="?",
         note="Z-saliency quadric scaling on ORGANIC (was c4-inert/noise; c3 is a different regime)"),
    dict(name="alloc_10",   family="ordering", kind="env", env={"G_ALLOC_WEIGHT": "1.0"}, expect="?",
         note="Z-saliency quadric scaling, full strength"),
    dict(name="zpen_3",     family="ordering", kind="env", env={"G_ZPEN": "3"}, expect="?",
         note="depth-steepness collapse deferral (c4-inert; organic re-screen)"),
    dict(name="hid_deep",   family="ordering", kind="patch", expect="?",
         subs=[("cost *= 1e-4;", "cost *= 1e-6;")],
         note="hidden-pair collapses even earlier (frees budget for visible verts)"),

    # ---------- B. KERNEL / PLACEMENT (the error metric and where the vertex lands) ----------
    dict(name="salcost_05", family="kernel", kind="patch", env={"G_SALCOST": "0.5"}, expect="?",
         subs=[
           ("static double g_margin   = std::numeric_limits<double>::infinity();",
            "static double g_salcost = 0.0; static std::vector<float> g_salw;\nstatic double g_margin   = std::numeric_limits<double>::infinity();"),
           ('if (const char* e = getenv("G_ALLOC_WEIGHT")) g_alloc_weight = atof(e);',
            'if (const char* e = getenv("G_ALLOC_WEIGHT")) g_alloc_weight = atof(e);\n    if (const char* e = getenv("G_SALCOST")) g_salcost = atof(e);'),
           ("if (g_alloc_weight > 0.0) {", "if (g_alloc_weight > 0.0 || g_salcost > 0.0) {"),
           ("Q[v] *= (1.0 + g_alloc_weight * (sd / se));",
            "{ const double sal = sd / se; if (g_alloc_weight > 0.0) Q[v] *= (1.0 + g_alloc_weight * sal); if (g_salcost > 0.0) { if (g_salw.empty()) g_salw.assign(nv, 0.f); g_salw[(size_t)v] = (float)sal; } }"),
           ("if (!g_rimw.empty()) cost *= (1.0 + g_rimK * (g_rimw[i] + g_rimw[j]));",
            "if (!g_rimw.empty()) cost *= (1.0 + g_rimK * (g_rimw[i] + g_rimw[j]));\n    if (!g_salw.empty()) cost *= (1.0 + g_salcost * (g_salw[i] + g_salw[j]));"),
         ],
         note="NEW: steepness-saliency as rim-style COST multiplier (allocation via ordering, not quadric scale)"),
    dict(name="salcost_10", family="kernel", kind="patch_reuse", reuse="salcost_05",
         env={"G_SALCOST": "1.0"}, expect="?", note="same binary as salcost_05, strength 1.0"),
    dict(name="subset_c3",  family="kernel", kind="env", env={"G_SUBSET": "1"}, expect="0",
         note="DEAD KNOB (found by zoo DUPE-detection): mein.cpp:1984 'g_subset_place = false' "
              "force-disables it 3 lines after the env read -> G_SUBSET has never engaged anywhere. "
              "Also corrects the c4-session conclusion (subset was never ON, see c4 MANIFEST erratum)."),
    dict(name="aniso_on",   family="kernel", kind="env", env={"G_ANISO": "1"}, expect="?",
         note="curvature-aligned placement candidates (banked on c4 CAD; 'dead on organic' verdict was OLD ruler)"),
    dict(name="deteps_8",   family="kernel", kind="patch", expect="?",
         subs=[("constexpr double kDetEps = 1e-10;", "constexpr double kDetEps = 1e-8;")],
         note="QEM solve regularization looser (more midpoint fallbacks on near-singular quadrics)"),
    dict(name="deteps_12",  family="kernel", kind="patch", expect="?",
         subs=[("constexpr double kDetEps = 1e-10;", "constexpr double kDetEps = 1e-12;")],
         note="QEM solve regularization tighter (trust the solve on flatter quadrics)"),
    dict(name="flip_m02",   family="kernel", kind="env", env={"G_FLIPTAU": "-0.2"}, expect="?",
         note="relax the normal-flip gate slightly on c3 (default 0.0 = strict)"),

    # ---------- C. TAIL (image-driven last collapses) ----------
    dict(name="pool_400",   family="tail", kind="env", env={"G_LAZY": "400"}, expect="?",
         note="lazy tail pool 700->400 (cheaper, earlier commit)"),
    dict(name="pool_1200",  family="tail", kind="env", env={"G_LAZY": "1200"}, expect="?",
         note="pool 700->1200 (deeper candidate set; judge-time irrelevant locally)"),
    dict(name="pool_2500",  family="tail", kind="env", env={"G_LAZY": "2500"}, expect="?",
         note="pool 2500: offline-depth probe - how much does an unaffordable tail buy?"),
    dict(name="ctb_50",     family="tail", kind="env", env={"G_CTB": "5.0"}, expect="?",
         note="tail box 6.5->5.0s (starved tail: measures the convergence margin)"),
    dict(name="ctb_85",     family="tail", kind="env", env={"G_CTB": "8.5"}, expect="?",
         note="tail box 6.5->8.5s (deeper converge)"),
    dict(name="rb_48",      family="tail", kind="patch", expect="?",
         subs=[("if (lzpool > 0) ctail_lazy(c3t, lzpool, 24, r_elapsed()+ctb);",
                "if (lzpool > 0) ctail_lazy(c3t, lzpool, 48, r_elapsed()+ctb);")],
         note="tail re-render burst 24->48 (fresher scores between renders)"),
    dict(name="rb_96",      family="tail", kind="patch", expect="?",
         subs=[("if (lzpool > 0) ctail_lazy(c3t, lzpool, 24, r_elapsed()+ctb);",
                "if (lzpool > 0) ctail_lazy(c3t, lzpool, 96, r_elapsed()+ctb);")],
         note="burst 96 (staler scores, more commits per render)"),
    dict(name="mpc_off",    family="tail", kind="env", env={"G_MPC": "0"}, expect="-",
         note="multi-placement OFF (judge-validated +: 6710 crossed with it) - semi-control"),
    dict(name="mpc_classic",family="tail", kind="env", env={"G_MPC": "1"}, expect="?",
         note="MPC classic only (no continuous line-search): is the line-search the active part?"),

    # ---------- D. POLISH / REFINE (the re-priced family: +4.3e-3 S2n measured headroom) ----------
    dict(name="mini_16",    family="polish", kind="env", env={"G_MINI": "16"}, expect="?",
         note="mini_refine iteration cap 8->16 (c3-determinism cap was chosen for TIME, not quality)"),
    dict(name="mini_32",    family="polish", kind="env", env={"G_MINI": "32"}, expect="?",
         note="cap 8->32: the c5-POLISH transplant, step 2"),
    dict(name="mini_64",    family="polish", kind="env", env={"G_MINI": "64"}, expect="?",
         note="cap 8->64: how much of the +4.3e-3 M0 headroom does the in-pipeline polish recover?"),
    dict(name="repair_20",  family="polish", kind="patch", expect="?",
         subs=[("mini_refine(1.2);", "mini_refine(2.0);")],
         note="repair-burst budget 1.2->2.0s (c5-polish analog on c3, budget axis)"),
    dict(name="repair_30",  family="polish", kind="patch", expect="?",
         subs=[("mini_refine(1.2);", "mini_refine(3.0);")],
         note="repair burst 3.0s"),
    dict(name="lsiter_2",   family="polish", kind="env", env={"G_LSITER": "2"}, expect="?",
         note="guided-seed->refine cycles x2 (family read +1.35e-4 at 1 iter)"),
    dict(name="lsiter_3",   family="polish", kind="env", env={"G_LSITER": "3"}, expect="?",
         note="seed cycles x3"),
    dict(name="lsres_768",  family="polish", kind="env", env={"G_LSRES": "768"}, expect="?",
         note="guided-seed at 768 instead of 1024 (cheaper seed -> budget freed downstream)"),
    dict(name="lac_05",     family="polish", kind="env", env={"G_LAC": "0.5"}, expect="?",
         note="AC-seed: laplacian-of-residual guided zigzag (exploratory, env semantics = strength)"),
    dict(name="budget_30",  family="polish", kind="patch", expect="?",
         subs=[("static double g_refine_budget = 16.0;", "static double g_refine_budget = 30.0;")],
         note="refine wall-clock 16->30s: the in-pipeline convergence ceiling (TLE-irrelevant locally)"),

    # ---------- E. SCHEDULE / STRUCTURE ----------
    dict(name="stage2_15",  family="schedule", kind="env", env={"G_2STAGE": "1.5"}, expect="?",
         note="bulk-QEM to 1.5x target then VSA-lite ordering (c7's speed trick, quality question on c3)"),
    dict(name="stage2_30",  family="schedule", kind="env", env={"G_2STAGE": "3.0"}, expect="?",
         note="bulk to 3x then ordered finish"),
    dict(name="redecim",    family="schedule", kind="patch", expect="?",
         subs=[("seed_heap(); Decimate(c3t);",
                "seed_heap(); Decimate(c3t + 400); { const int _sm = g_mini_maxit; g_mini_maxit = 6; mini_refine(0.9); g_mini_maxit = _sm; } seed_heap(); Decimate(c3t);")],
         note="decimate->refine->RE-decimate lite (Road B item 2: ordering re-run on SSIM-optimal geometry)"),
    dict(name="sil2_400",   family="schedule", kind="patch", expect="?",
         subs=[("sil2_pass(200, 1);", "sil2_pass(400, 1);")],
         note="silhouette pass 200->400 evals (judge-costed +1.8s; local quality read)"),
    dict(name="c3t_6700",   family="schedule", kind="env", env={"G_C3T": "6700"}, expect="+",
         note="S(N) curve point above (sanity: MUST read above base)"),
    dict(name="c3t_6500",   family="schedule", kind="env", env={"G_C3T": "6500"}, expect="-",
         note="S(N) below the wall: the deficit any 91-mechanism must cover at 6500"),
    dict(name="c3t_6400",   family="schedule", kind="env", env={"G_C3T": "6400"}, expect="-",
         note="S(N) at 6400 (91-arithmetic anchor: 6040 needed for 91-via-c3-alone)"),

    # ---------- WAVE 2 (2026-07-15): map the stage2 curve + stack the two cheap winners ----------
    # stage2_30 = the only CROSS-MESH winner of pass 1/2 (+0.0015 happy / +0.0016 dragon) and it is
    # FASTER than base (6.4s vs 7.9s). stage2_15 HURTS (-0.0025 happy) -> non-monotone, map the peak.
    dict(name="stage2_20",  family="schedule", kind="env", env={"G_2STAGE": "2.0"}, expect="?",
         note="wave2: bulk-QEM to 2.0x then ordered finish (curve point)"),
    dict(name="stage2_25",  family="schedule", kind="env", env={"G_2STAGE": "2.5"}, expect="?",
         note="wave2: bulk to 2.5x (curve point)"),
    dict(name="stage2_40",  family="schedule", kind="env", env={"G_2STAGE": "4.0"}, expect="?",
         note="wave2: bulk to 4.0x (curve point)"),
    dict(name="stage2_50",  family="schedule", kind="env", env={"G_2STAGE": "5.0"}, expect="?",
         note="wave2: bulk to 5.0x (curve point; more bulk = faster but ordering sees less)"),
    dict(name="s3_mini16",  family="schedule", kind="env", env={"G_2STAGE": "3.0", "G_MINI": "16"}, expect="?",
         note="wave2 COMBO: the two cheap positives stacked (stage2_30 + polish cap 16)"),
    dict(name="s3_mini32",  family="schedule", kind="env", env={"G_2STAGE": "3.0", "G_MINI": "32"}, expect="?",
         note="wave2 COMBO: stage2_30 + polish cap 32"),

    # ---------- WAVE 3 (2026-07-15): the polish-cap pursuit (the surviving path) ----------
    # mini_16 grows below the wall (+0.0014 @6610 -> +0.0026 @6500) with ~zero time cost, is
    # mechanism-monotone (no basin re-roll), and matches M0's +4.3e-3 convergence ceiling.
    dict(name="mini_12",    family="polish", kind="env", env={"G_MINI": "12"}, expect="?",
         note="wave3: cap curve point below 16 (where does the gain start?)"),
    dict(name="mini_24",    family="polish", kind="env", env={"G_MINI": "24"}, expect="?",
         note="wave3: cap curve point between 16 and 32 (saturation shape)"),
]
